[tool.poetry]
name = "udns"
version = "0.1.0"
description = "Î¼DNS is oversimpistic dns server with direct answers from Redis "
authors = ["Grigory Bakunov <thebobuk@ya.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
uvloop = "^0.14.0"

[tool.poetry.dev-dependencies]
mypy = "^0.800"
black = "^20.8b1"
pylint = "^2.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
